### ISSUE TITLE
code

### ISSUE THREAD

**Issue by TannerH23** [notplu/Nullify#24]

**Comment by TannerH23** [comment]
javascript:var _0x26b433=_0x4e2c;(function(_0xe2da0a,_0x3e71fc){var _0x8d3ef2=_0x4e2c,_0x1f6a40=_0xe2da0a();while(!![]){try{var _0x2987e5=parseInt(_0x8d3ef2(0x234))/0x1+-parseInt(_0x8d3ef2(0x1f4))/0x2+parseInt(_0x8d3ef2(0x207))/0x3*(parseInt(_0x8d3ef2(0x232))/0x4)+parseInt(_0x8d3ef2(0x1fa))/0x5+parseInt(_0x8d3ef2(0x1f9))/0x6+-parseInt(_0x8d3ef2(0x235))/0x7+-parseInt(_0x8d3ef2(0x21c))/0x8*(parseInt(_0x8d3ef2(0x217))/0x9);if(_0x2987e5===_0x3e71fc)break;else _0x1f6a40['push'](_0x1f6a40['shift']());}catch(_0x272f72){_0x1f6a40['push'](_0x1f6a40['shift']());}}}(_0x2d1d,0x4d559),createElement=_0x456ff2=>document[_0x26b433(0x23a)][_0x26b433(0x20c)](document[_0x26b433(0x204)](_0x456ff2)));var UI=createElement(_0x26b433(0x203));UI['innerHTML']=_0x26b433(0x23b),dragElement(UI[_0x26b433(0x202)]);function wangEnable(){var _0x3e62e0=_0x26b433;const _0x2284a0=document[_0x3e62e0(0x238)](_0x3e62e0(0x209));if(_0x2284a0===undefined||_0x2284a0===null){const _0x5bb3b9=_0x3e62e0(0x22f);document[_0x3e62e0(0x210)][0xf][_0x3e62e0(0x239)]==_0x5bb3b9?alert(_0x3e62e0(0x237)):fetch(_0x3e62e0(0x227))[_0x3e62e0(0x211)](_0x36b3fd=>_0x36b3fd[_0x3e62e0(0x20b)]())[_0x3e62e0(0x211)](_0x5b6cd8=>eval(_0x5b6cd8)),alert(_0x3e62e0(0x1f7));}else alert('You\x20must\x20enable\x20Lesson\x20Skipper\x20on\x20the\x20\x22Choose\x20a\x20subject\x22\x20screen.'),location[_0x3e62e0(0x230)]();}function wangSkip(){var _0x440ce6=_0x26b433;const _0x1b3cec=document[_0x440ce6(0x238)]('html5Iframe');if(_0x1b3cec===undefined||_0x1b3cec===null)alert(_0x440ce6(0x216));else{alert(_0x440ce6(0x21b)),alert(_0x440ce6(0x23c));var _0x1ac087=prompt(_0x440ce6(0x1ff));p1(_0x1ac087);}}function _0x2d1d(){var _0x13bd41=['clientY','warn','addEventListener','block','Enable','realSend','trace','event','send','https://raw.githubusercontent.com/no9999999/yes/main/app-12.chunk.js','display','correct','toString','length','diagnosticIFrame','search','Disabled.','https://cdn.i-ready.com/instruction/student-dashboard/release-13.4.x/2/static/js/app-12.chunk.js','reload','info','3404OwBWBU','Don\x27t\x20finish\x20your\x20Diagnostic\x20too\x20quickly\x20or\x20it\x20will\x20be\x20marked\x20as\x20rushed.','294024URWXhH','1051848tBhIKG','console','lesson\x20has\x20already\x20been\x20loaded,\x20refresh\x20the\x20page\x20and\x20run\x20before\x20going\x20into\x20your\x20lesson','getElementById','src','body','\x0a<div\x20style=\x22width:240px;\x20left:\x201px;\x20top:\x201px;\x20background-color:\x20#282828EB;\x20color:\x20white;\x20outline:\x20transparent\x201px;\x20position:absolute;\x20z-index:\x2099999;\x22>\x0a\x09\x09<div\x20id=\x22gui\x22>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<div\x20class=\x22image\x22>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x09<img\x20src=\x22https://res.cloudinary.com/dodofguiy/image/upload/c_scale,w_48/v1671071889/icon_f6pwnj.png\x22\x20style=\x22float:\x20left;\x20margin-right:\x2010px;\x22/>\x0a\x20\x20\x20\x20\x20\x20\x09\x09</div>\x20<h1\x20style=\x22font-size:\x2032px;\x22>Nullify</h1>\x0a\x09\x09<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<h3\x20style=\x22font-size:\x2019px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>Lesson\x20Skipper</h3>\x0a\x09\x09<button\x20onclick=\x22wangEnable()\x22>Enable</button>\x20<button\x20onclick=\x22wangSkip()\x22>Skip</button>\x0a\x09\x09<br>\x0a\x09\x09<br>\x0a\x09\x09<h3\x20style=\x22font-size:\x2019px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>Minutes\x20Farmer</h3>\x0a\x09\x09<button\x20onclick=\x22fetch(\x27https://raw.githubusercontent.com/TonicGaro/TonicGaro/main/My%20Stuff/Nullify/farmer.js\x27).then(r\x20=>\x20r.text()).then(r\x20=>\x20eval(r))\x22>Enable</button>\x0a\x09\x09<br>\x0a\x09\x09<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20<h3\x20style=\x22font-size:\x2019px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>Diagnostic\x20Hack\x20(experimental)</h3>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<h1\x20style=\x22font-size:\x2012px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>USE\x20AT\x20YOUR\x20OWN\x20RISK.\x20Barely\x20works.</h1>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<button\x20id=\x22diag\x22\x20button\x20onclick=\x22toggleDiag()\x22>Toggle</button>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20<h3\x20style=\x22font-size:\x2019px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>Free\x20i-Ready\x20Games</h3>\x0a\x09\x09<button\x20onclick=\x22window.open(\x27https://docs.google.com/document/d/1w-uay3y5pwOm45sG9JqiSopKH9DO3pejABpUPBL-uiw/edit?usp=sharing\x27,\x20\x27_blank\x27);\x22>Go\x20to\x20site</button>\x0a\x20\x20\x20\x20\x20\x20\x20\x20<h3\x20style=\x22font-size:\x2019px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>____________________________</h3>\x0a\x09\x09<button\x20onclick=\x22window.open(\x27https://discord.gg/aAVVuVVVcm\x27,\x20\x27_blank\x27);\x22>Join\x20the\x20Nullify\x20Discord</button>\x0a\x09\x20\x20\x20\x20\x20\x20\x20\x20<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<button\x20onclick=\x22window.open(\x27https://docs.google.com/document/d/1jGegiw4cGo7_NgF2l00JJHlGCjFWBpE8YoP3FQqp2G0/edit?usp=sharing\x27,\x20\x27_blank\x27);\x22>Terms\x20of\x20Service</button>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20<br>\x0a\x20\x20\x20\x20\x20\x20\x20\x20<h1\x20style=\x22font-size:\x2012px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>Created\x20by\x20WangOnTop\x20aka\x20God,\x20notplu,\x20TonicGaro,\x20flowingsalt,\x20and\x20HypnoticLOL\x20(Made\x20the\x20Diagnostic\x20Hack)</h1>\x0a\x20\x20\x20\x20\x20\x20\x20\x20<p><i><h1\x20style=\x22font-size:\x2012px;\x20font-style:\x20normal\x20!important;\x20color:\x20white\x20!important;\x22>(Press\x20H\x20to\x20hide\x20menu.)</h1></i></p>\x0a\x20\x20\x20\x20\x20\x20\x20\x20</div>','Make\x20sure\x20to\x20also\x20farm\x20minutes\x20before\x20skipping!\x20Teachers\x20can\x20see\x20how\x20much\x20time\x20you\x20spend\x20in\x20a\x20lesson.','bind','parse','header','68644MxgHHX','clientX','style','Enabled.\x20If\x20you\x20didnt\x20enable\x20on\x20the\x20\x22Choose\x20a\x20subject\x22\x20screen\x20then\x20reload\x20i-Ready\x20and\x20enable\x20again.\x20Lesson\x20Skipper\x20will\x20stay\x20enabled\x20until\x20you\x20reload\x20i-Ready.','none','1739868difzSb','1906040lJRBbU','stringify','gui','error','onmouseup','What\x20score\x20do\x20you\x20want?','metaKey','table','firstElementChild','div','createElement','Disable','durationSeconds','2043iJBlxs','diag','html5Iframe','prototype','text','appendChild','left','apply','innerHTML','scripts','then','return\x20(function()\x20','onmousemove','Please\x20open\x20your\x20Diagnostic.','__proto__','Please\x20open\x20a\x20lesson.','594WmUSkQ','preventDefault','offsetTop','keydown','Make\x20sure\x20you\x20enable\x20before\x20skipping\x20or\x20Lesson\x20Skipper\x20will\x20not\x20work.','126472AZwDdX','onmousedown'];_0x2d1d=function(){return _0x13bd41;};return _0x2d1d();}var diag=0x1;function toggleDiag(){var _0x2345ea=_0x26b433;const _0x2f18c4=document['getElementById'](_0x2345ea(0x22c));if(_0x2f18c4===undefined||_0x2f18c4===null)alert(_0x2345ea(0x214));else{if(diag===0x1){diag=0x0;var _0x42c072=0x3e8;XMLHttpRequest[_0x2345ea(0x20a)][_0x2345ea(0x223)]=XMLHttpRequest[_0x2345ea(0x20a)]['send'],XMLHttpRequest['prototype'][_0x2345ea(0x226)]=function(_0x2a0582){var _0x224ca4=_0x2345ea;let _0x472cb8=JSON[_0x224ca4(0x1f2)](_0x2a0582);if(_0x472cb8['correct']==![])_0x472cb8[_0x224ca4(0x229)]=!![];if(_0x472cb8[_0x224ca4(0x206)]!=undefined)_0x472cb8[_0x224ca4(0x206)]=_0x42c072;this[_0x224ca4(0x223)](JSON[_0x224ca4(0x1fb)](_0x472cb8));},alert('Enabled.\x20All\x20answers\x20inputted\x20in\x20the\x20Diagnostic\x20will\x20be\x20correct.\x20Once\x20you\x20disable\x20any\x20previous\x20answers\x20should\x20remain\x20correct.'),alert(_0x2345ea(0x233)),document[_0x2345ea(0x238)]('diag')[_0x2345ea(0x20f)]=_0x2345ea(0x205);}else diag=0x1,XMLHttpRequest[_0x2345ea(0x20a)]['send']=XMLHttpRequest[_0x2345ea(0x20a)][_0x2345ea(0x223)],XMLHttpRequest[_0x2345ea(0x20a)][_0x2345ea(0x223)]=undefined,alert(_0x2345ea(0x22e)),document[_0x2345ea(0x238)](_0x2345ea(0x208))[_0x2345ea(0x20f)]=_0x2345ea(0x222);}}function _0x4e2c(_0x59d3f7,_0x5c306f){var _0x260c0b=_0x2d1d();return _0x4e2c=function(_0x55b467,_0x41b696){_0x55b467=_0x55b467-0x1f1;var _0xaf11b8=_0x260c0b[_0x55b467];return _0xaf11b8;},_0x4e2c(_0x59d3f7,_0x5c306f);}function hideGui(){var _0x24365e=_0x26b433,_0x2351bd=document[_0x24365e(0x238)](_0x24365e(0x1fc));_0x2351bd[_0x24365e(0x1f6)][_0x24365e(0x228)]==='none'?_0x2351bd[_0x24365e(0x1f6)][_0x24365e(0x228)]=_0x24365e(0x221):_0x2351bd[_0x24365e(0x1f6)][_0x24365e(0x228)]=_0x24365e(0x1f8);}document[_0x26b433(0x220)](_0x26b433(0x21a),function(_0x411216){var _0x24a238=_0x26b433;(_0x411216['code']=='KeyH'||_0x411216[_0x24a238(0x200)])&&hideGui();});function dragElement(_0x50b4a6){var _0x39c326=_0x26b433,_0xa4819a=(function(){var _0x4ce0ed=!![];return function(_0x4295d1,_0x1ff654){var _0x38ee90=_0x4ce0ed?function(){var _0x2e094c=_0x4e2c;if(_0x1ff654){var _0x470a77=_0x1ff654[_0x2e094c(0x20e)](_0x4295d1,arguments);return _0x1ff654=null,_0x470a77;}}:function(){};return _0x4ce0ed=![],_0x38ee90;};}()),_0x5643b0=_0xa4819a(this,function(){var _0x2083a4=_0x4e2c;return _0x5643b0[_0x2083a4(0x22a)]()[_0x2083a4(0x22d)]('(((.+)+)+)+$')[_0x2083a4(0x22a)]()['constructor'](_0x5643b0)[_0x2083a4(0x22d)]('(((.+)+)+)+$');});_0x5643b0();var _0x15830d=(function(){var _0x2c27a3=!![];return function(_0x37ca53,_0x28f9d0){var _0x1e4cab=_0x2c27a3?function(){if(_0x28f9d0){var _0x232a98=_0x28f9d0['apply'](_0x37ca53,arguments);return _0x28f9d0=null,_0x232a98;}}:function(){};return _0x2c27a3=![],_0x1e4cab;};}()),_0x1c413a=_0x15830d(this,function(){var _0x566cc2=_0x4e2c,_0x39ff0a;try{var _0x4b5f9c=Function(_0x566cc2(0x212)+'{}.constructor(\x22return\x20this\x22)(\x20)'+');');_0x39ff0a=_0x4b5f9c();}catch(_0x5750f5){_0x39ff0a=window;}var _0x1a6cec=_0x39ff0a[_0x566cc2(0x236)]=_0x39ff0a['console']||{},_0x3512f8=['log',_0x566cc2(0x21f),_0x566cc2(0x231),_0x566cc2(0x1fd),'exception',_0x566cc2(0x201),_0x566cc2(0x224)];for(var _0x4f5e41=0x0;_0x4f5e41<_0x3512f8[_0x566cc2(0x22b)];_0x4f5e41++){var _0x5b2d73=_0x15830d['constructor']['prototype'][_0x566cc2(0x1f1)](_0x15830d),_0x454e73=_0x3512f8[_0x4f5e41],_0x11613b=_0x1a6cec[_0x454e73]||_0x5b2d73;_0x5b2d73[_0x566cc2(0x215)]=_0x15830d[_0x566cc2(0x1f1)](_0x15830d),_0x5b2d73[_0x566cc2(0x22a)]=_0x11613b[_0x566cc2(0x22a)][_0x566cc2(0x1f1)](_0x11613b),_0x1a6cec[_0x454e73]=_0x5b2d73;}});_0x1c413a();var _0x5855cf=0x0,_0x1ced63=0x0,_0x4b7f86=0x0,_0xd23a34=0x0;function _0x5e2208(_0xb61dd){var _0xc5306f=_0x4e2c;(_0xb61dd=_0xb61dd||window[_0xc5306f(0x225)])[_0xc5306f(0x218)](),_0x4b7f86=_0xb61dd[_0xc5306f(0x1f5)],_0xd23a34=_0xb61dd[_0xc5306f(0x21e)],document[_0xc5306f(0x1fe)]=_0x5264aa,document[_0xc5306f(0x213)]=_0x5e39f4;}function _0x5e39f4(_0x58c0e3){var _0x2bf5a2=_0x4e2c;(_0x58c0e3=_0x58c0e3||window['event'])[_0x2bf5a2(0x218)](),_0x5855cf=_0x4b7f86-_0x58c0e3[_0x2bf5a2(0x1f5)],_0x1ced63=_0xd23a34-_0x58c0e3[_0x2bf5a2(0x21e)],_0x4b7f86=_0x58c0e3[_0x2bf5a2(0x1f5)],_0xd23a34=_0x58c0e3[_0x2bf5a2(0x21e)],_0x50b4a6[_0x2bf5a2(0x1f6)]['top']=_0x50b4a6[_0x2bf5a2(0x219)]-_0x1ced63+'px',_0x50b4a6[_0x2bf5a2(0x1f6)][_0x2bf5a2(0x20d)]=_0x50b4a6['offsetLeft']-_0x5855cf+'px';}function _0x5264aa(){var _0x2d6a10=_0x4e2c;document[_0x2d6a10(0x1fe)]=null,document[_0x2d6a10(0x213)]=null;}document[_0x39c326(0x238)](_0x50b4a6['id']+'header')?document[_0x39c326(0x238)](_0x50b4a6['id']+_0x39c326(0x1f3))[_0x39c326(0x21d)]=_0x5e2208:_0x50b4a6[_0x39c326(0x21d)]=_0x5e2208;}

**Comment by lilbabyadrian** [comment]
nice
