### ISSUE TITLE
Lesson Skipper is broke

### ISSUE THREAD

**Issue by ReSteGuy** [notplu/Nullify#31]
![image](https://user-images.githubusercontent.com/63218795/217081437-fb56e60d-f439-45b3-900a-48996dcbc3c2.png)
IDK why.

**Comment by TonicGaro** [comment]
Issue should've been fixed yesterday as we updated our modified app chunk. Did this occur just now?

**Comment by ReSteGuy** [comment]
yeah, its fixed now i just swapped it out with the github booklet
