### ISSUE TITLE
Bug or Issue?

### ISSUE THREAD

**Issue by Layah2Playerr** [notplu/Nullify#37]
The farm minutes aren't working.

**Comment by Layah2Playerr** [comment]
> The farm minutes aren't working.

What do I fix or do??

**Comment by thedudethatfamrs** [comment]
says to open a lesson even though the less is open, how do I fix this?

**Comment by thedudethatfamrs** [comment]
man your discord mods are actually pices of sh am trying tell them a issue and they mute me for a whole months the worst custoemer service I ever saw

**Comment by TonicGaro** [comment]
Sorry if the mods have been causing issues towards you. To fix your problem, you might need to simply update the version of Nullify you're currently using.

Here is the code for the latest version:
`javascript:fetch('https://raw.githubusercontent.com/notplu/Nullify/main/Data/main.js').then(r => r.text()).then(r => eval(r))`
