### ISSUE TITLE
The menu not opening on chromebooks issue explained.

### ISSUE THREAD

**Issue by DeadlyBman** [notplu/Nullify#38]
hello, since no onw has the iq to explain their problem I will. So what has been happening on chromebooks is where we copy the code like we always used to, do the bookmarklet like we used to, open Iready and click the bookmarklet and nothing would pop up. (this works fine on my windows pc which I am writing this on.

**Comment by DeadlyBman** [comment]
If anyone wants clearer info add me on discord  DeadlyBman109#6277

**Comment by notplu** [comment]
they prob blocked github website on your school wifi
