### ISSUE TITLE
Wheres the download for Nullify

### ISSUE THREAD

**Issue by Youllneverknowwhoiam1234** [notplu/Nullify#41]
When i try to paste the code for i-ready into the console it says i need to have nullify open. Where can i download nullify?

**Comment by TonicGaro** [comment]
I'm not completely sure what your asking here but it sounds like you just need to run Nullify before opening a lesson. You don't need to download Nullify either.

**Comment by Youllneverknowwhoiam1234** [comment]
how exactly do i run it then?

**Comment by Youllneverknowwhoiam1234** [comment]
> I'm not completely sure what your asking here but it sounds like you just need to run Nullify before opening a lesson. You don't need to download Nullify either.

how do i run it then?

**Comment by notplu** [comment]
Join our discord, there is a tutorial on how to install.

**Comment by Youllneverknowwhoiam1234** [comment]
> Join our discord, there is a tutorial on how to install.

alright thanks

**Comment by Youllneverknowwhoiam1234** [comment]
> Join our discord, there is a tutorial on how to install.

what channel is it in

**Comment by notplu** [comment]
hacks

**Comment by Youllneverknowwhoiam1234** [comment]
> hacks

i do not see a channel called hacks.

**Comment by Youllneverknowwhoiam1234** [comment]
> hacks

![Screenshot_20230216_060730](https://user-images.githubusercontent.com/125613620/219508598-5dcc1ca9-da00-4fa9-8ef7-1a3205fd130f.png)

**Comment by notplu** [comment]
go in nullify

**Comment by Youllneverknowwhoiam1234** [comment]
> go in nullify channel

sry for the troubles, thank you.

**Comment by notplu** [comment]
np

**Comment by Youllneverknowwhoiam1234** [comment]
I am using microsoft edge I don't know if that makes any difference but i tried to do all the steps in the video but it did not work.

**Comment by notplu** [comment]
say hi in the general and I can help you
